import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import Navbar from '@/components/Navbar';

import SvgSprites from '@/UI/SvgSprites';

import './globals.scss';

const roboto = Roboto({ variable: '--roboto-font', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'KTube',

    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={roboto.className}>
                <SvgSprites />

                <div className='main-content'>
                    <Navbar />

                    {children}
                </div>
            </body>
        </html>
    );
}
