import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import './globals.css';

const roboto = Roboto({ variable: '--roboto-font', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'K Tube',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={roboto.className}> {children} </body>
        </html>
    );
}
