name: CI

on:
  push:
    branches: '**'

jobs:
  sharedCI:
    name: shared CI

    runs-on: ubuntu-latest
    defaults:
      run:

        working-directory: shared

    steps:
    - uses: actions/checkout@v4

    - name: set up bun

      uses: oven-sh/setup-bun@v2

    - name: install dependencies
      run: bun install

    - name: run linter

      run: bun run lint

    - name: build
      run: bun run build

  frontendCI:
    needs: sharedCI
    name: Frontend CI

    runs-on: ubuntu-latest

    defaults:
      run:

        working-directory: frontend

    steps:
    - uses: actions/checkout@v4

    - name: build shared

      working-directory: shared
      run: bun install && bun run build

    - name: Install dependencies
      run: bun install

    - name: Run Linter
      run: bun run lint

    - name: Run tests
      run: bun run test

    - name: Build frontend
      run: bun build

  backendCI:
    needs: sharedCI
    name: backend CI

    runs-on: ubuntu-latest

    defaults:
      run:

        working-directory: backend

    steps:
    - uses: actions/checkout@v4

    - name: set up bun
      uses: oven-sh/setup-bun@v2

    - name: build shared
      working-directory: shared
      run: bun install && bun run build

    - name: Install dependencies
      run: bun install

    - name: run linter
      run: bun run lint

    - name: run tests
      run: bun test

    - name: build
      run: bun run build
